import Head from 'next/head'
import React from 'react'

const Header = () => {
  return (
    <>
      <Head>
        <title>Work Out</title>

        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="description"
          property="og:description"
          content="자신의 운동을 기록하세요."
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
    </>
  )
}

export default Header
