import Head from 'next/head'
import Script from 'next/script'
import React from 'react'
import { useRecoilState } from 'recoil'
import { ARemainTime } from '../../recoil/AllAtom'

const Header = () => {
  const [normalRemainTime, setNormalRemainTime] = useRecoilState(ARemainTime)

  return (
    <>
      <Head>
        <title>Work Out {normalRemainTime.first}</title>

        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="description"
          property="og:description"
          content="자신의 운동을 기록하세요."
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
    </>
  )
}

export default Header
