import { ReactElement, useContext, useEffect, useState } from 'react'

import Head from 'next/head'

import Header from '../organisms/Header'
import Navigator from '../organisms/Navigator'
import { getMyAuth } from '../../firebase/auth/Auth'
import { onAuthStateChanged } from 'firebase/auth'
import { authLoading, userInfo } from '../../recoil/ExercisesState'
import { useRecoilState } from 'recoil'
import styled from 'styled-components'
import TempNav from '../organisms/TempNav'
import { useAuth } from './useAuth'
import { useAuthInit } from './useAuthInit'

type LayoutProps = {
  children: ReactElement
}

const Container = styled.div`
  width: 100%;
  background-color: ${(props) => props.theme.colors.black};
  margin: 0 auto 0;
`

const Layout = ({ children }: LayoutProps) => {
  useAuthInit()
  return (
    <Container>
      <Head>
        <title>Work Out</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="description"
          property="og:description"
          content="자신의 운동을 기록하세요."
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      {/* {activeNotification && (
        <Notification
          message={'123'}
          status={true}
          title={'title'}
        />
      )} */}

      {/* <Header /> */}
      <TempNav />

      {children}

      {/* <Navigator /> */}
    </Container>
  )
}

export default Layout
