import axios from 'axios';
import { ReactElement } from 'react';
import useSWR from 'swr';

import Head from 'next/head';

import styles from './layout.module.css'

type LayoutProps = {
    children: ReactElement
}

const fetcher = (url: string) => axios.get(url).then(res => res.data)

const Layout = ({ children }: LayoutProps) => {
    const { data, error } = useSWR('/api/hello', fetcher)

    if (error) return <div>Failed to load</div>
    if (!data) return <div>Loading...</div>

  return (
    <div className={styles.container} >
      <Head>
        <title>Work Out</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {children}
    </div>
  )
}

export default Layout