import { ReactElement, useContext, useEffect, useState } from 'react'

import Head from 'next/head'

import styles from './layout.module.css'
import Header from '../organisms/Header'
import Navigator from '../organisms/Navigator'
import NotificationContext from '../../store/NotificationContext'
import { getMyAuth } from '../../utils/firebase/Auth'
import { onAuthStateChanged } from 'firebase/auth'
import { authLoading, userInfo } from '../../utils/recoil/ExercisesState'
import { useRecoilState } from 'recoil'

type LayoutProps = {
  children: ReactElement
}

const Layout = ({ children }: LayoutProps) => {
  const [loading, setLoading] = useRecoilState(authLoading)
  const [user, setUser] = useRecoilState(userInfo)

  useEffect(() => {
    const auth = getMyAuth()
    const listener = onAuthStateChanged(auth.auth, (user) => {
      if (user) {
        const uid = user.uid
        setUser({
          email: user.email!,
          displayName: user.displayName!,
        })
        setLoading(false)
      } else {
        setLoading(false)
      }
    })

    return () => {
      listener()
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Work Out</title>
        <meta
          name="description"
          content="Generated by create next app"
        />

        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      {/* {activeNotification && (
        <Notification
          message={'123'}
          status={true}
          title={'title'}
        />
      )} */}
      <Header />

      {children}

      <Navigator />
    </div>
  )
}

export default Layout
